### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by njelly** [njelly/TofuECS#2]
I've worked a bit on the README to give a high level explanation of TofuECS, but the code itself needs documentation - in the form of XML tags above method definitions, auto-generated mark down files, etc. I'll work on this over time now that I feel the framework is feature complete.

Anyone else that would like to contribute is welcome to do so.

**Comment by MindSwipe** [comment]
I just created a PR (#5) that adds a demo project showcasing how to use the ECS in it's current state

**Comment by njelly** [comment]
> I just created a PR (#5) that adds a demo project showcasing how to use the ECS in it's current state

Thanks! I'll take a look when I have more time. I'm not entirely sure if it will be necessary as my intention is to have a Unity project in a separate repo as a practical demo, and to have the unit tests sort of point the way for users for now.

It's very cool to see some one else using my code, even if it's for a small demo haha. :)
